[entryPoints]

 [entryPoints.web]
      address = ":80"

    [entryPoints.websecure]
      address = ":443"

    [entryPoints.httpserver_1]
      address = ":8888"

    [entryPoints.httpserver_2]
      address = ":8887"

    [entryPoints.tcpserver_1]
      address = ":8886"

[providers]

  # DOCKER

  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

  # FILE
  
  [providers.file]
    [[providers.file.endpoints]]
    name = "httpserver_1"
    localaddr = ":7777"
    remoteaddr = ":9595"

    [[providers.file.endpoints]]
    name = "httpserver_2"
    localaddr = "7776"
    remoteaddr = "9594"

    [[providers.file.endpoints]]
    name = "tcpserver_1"
    localaddr = "7775"
    remoteaddr = "9593"