[entryPoints]

 [entryPoints.web]
      address = ":80"

    [entryPoints.websecure]
      address = ":443"

    [entryPoints.httpserver_1]
      address = ":8888"

    [entryPoints.httpserver_2]
      address = ":8887"

    [entryPoints.tcpserver_1]
      address = ":8886"

[providers]

  # DOCKER

  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

  # FILE
  
  [providers.file]
    endpoint = "unix:///var/run/docker.sock"