[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
  endpoint = "unix:///var/run/docker.sock"

  # Default: "Host(`{{ normalize .Name }}`)"
  # defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"