[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.service-1]
    address = ":8080"

  [entryPoints.service-2]
    address = ":8081"

[providers]
  [providers.docker]
  endpoint = "unix:///var/run/docker.sock"

  # Default: "Host(`{{ normalize .Name }}`)"
  # defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"